# Docker Compose 配置 - 本地构建版本
# 适用于开发和自定义构建

services:
  apikey-king:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apikey-king
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

