# Default configuration for APIKEY-king
# This file contains default values that can be overridden by environment variables

# Application settings
data_path: "./data"
proxy: ""

# GitHub configuration
github_tokens: ""
github_api_url: "https://api.github.com/search/code"

# Scanning configuration
date_range_days: 730
file_path_blacklist: "readme,docs,doc/,.md,example,sample,tutorial,test,spec,demo,mock"
queries_file: "config/queries/default.txt"

# Logging configuration
log_level: "INFO"
enable_file_logging: true